[tool.poetry]
name = "Dirlin"
version = "0.2.0"
description = "Handy functions for local files"
authors = ["mendozasho"]
readme = "README.md"

packages = [{include = "dirlin"}]

[tool.poetry.dependencies]
python = "^3.11"
numpy="2.0.0"
pandas = "2.2.2"
openpyxl = "3.1.2"
xlrd = "2.0.1"
pyxlsb="1.0.10"
pathlib = "1.0.1"
chardet = "5.2.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
